### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by gBopHuk** [potz/docker-gnucash#1]
What does it provide?
How to run it?
Any examples?

**Comment by potz** [comment]
To be honest is a nightmare to get this running on a Mac with XQuartz, I kinda gave up for now.

**Comment by gBopHuk** [comment]
How about Linux or Docker?

**Comment by potz** [comment]
My original usecase was for running this on the Mac, haven't tried with Linux. This was really just an experiment, I'll delete the repo.
